name: Documentation
description: Improve public documentation or examples
title: "[Docs]: "
labels: [documentation]
body:
  - type: textarea
    id: location
    attributes:
      label: Documentation location
      description: Link to the file or section that needs improvement.
    validations:
      required: true
  - type: textarea
    id: change
    attributes:
      label: Suggested improvement
    validations:
      required: true
